imagesearch/core/urls.py
from django.conf.urls import patterns, url
from views import *


urlpatterns = patterns('core.views',
  url(r'search/$', search, name='search'),
  url(r'fileupload/upload-file/$',upload_file, name='upload_file'),
  url(r'fileupload/upload-file-bank/$',upload_file_bank, name='upload_file_bank')
)

imagesearch/imagesearch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'core.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^core/', include('core.urls', namespace='core'))
]

urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagesearch/core/models.py
from django.db import models

# Create your models here.

imagesearch/core/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import json
import traceback
import json
import uuid
import re
import tempfile
import wand.image
import wand.display
import wand.exceptions
import os

from os import listdir
from os.path import isfile, join

from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core.urlresolvers import reverse




#local stuff
from img import persisted_img
im = persisted_img()

BANK_PATH = 'static/img/bank'
BANK_THUMB_PATH = join(BANK_PATH,'thumb')

def get_images(path):
    #Need to change this
    return filter(
        lambda x : re.search('\.(jpg|jpeg|png)', x.lower()) != None,
        [join(path, f) for f in listdir(path) if isfile(join(path,f))]
    )

def get_bank_images():
    return get_images(BANK_PATH)

def get_thumb_images():
    return get_images(BANK_THUMB_PATH)


def home(request):
    return render(request, 'base.html', {})


def search(request):
    if request.method == 'GET':
        img_name = request.GET.get('f')
        file_path = join(settings.MEDIA_ROOT, img_name)
        file = open(file_path, 'r+')
        if file:
            # try:
            with wand.image.Image(filename=file_path) as img:
                img.resize(256, 256)
                img.save(filename=file_path)
            matches = im.match(file_path, limit=10)
            print len(matches)
            return render(request, 'base.html',
                          {'media_url': settings.MEDIA_URL,
                          'image_name': img_name,
                          'image_matches': matches}
                        )

            # except:
            #     traceback.print_exc()
            #     return render(request, 'base.html',
            #                   {'media_url': settings.MEDIA_URL,
            #                   'image_name': img_name,
            #                   'image_matches': []}
            #                 )


@csrf_exempt
def upload_file(request):
    # Save the image object in the media folder and proceed to search
    if request.method == 'POST':
        is_file = request.FILES.get('file')
        print is_file
        if is_file:
            if not os.path.exists(settings.MEDIA_ROOT + '/' + str(is_file.name)):
                default_storage.save(settings.MEDIA_ROOT + '/'
                    + str(is_file.name), ContentFile(is_file.read()))
            response = {'filename': is_file.name,
                        'media_url': settings.MEDIA_URL}
            return HttpResponse(json.dumps(response))
        else:
            msg = 'Something has went wrong, please try again.'
            return HttpResponse(msg)
    else:
        return render(request, 'base.html', {})

def upload_file_bank(request):
    # Save images in the bank
    if request.method == 'POST':
        file = request.FILES.get('file')
        if file:
            # Create the temporary file for search operation
            file_path = default_storage.save(settings.MEDIA_ROOT + '/'
                    + str(file.name), ContentFile(file.read()))
            guid = str(uuid.uuid4().get_hex().upper()[0:12]) + '.jpg'
            dstfile = join(
                BANK_PATH,
                guid
            )
            dstfile_thumb = join(
                BANK_THUMB_PATH,
                guid
            )
            try:
                with wand.image.Image(filename=file_path) as img:
                    img.save(filename=dstfile)
                    img.resize(256, 256)
                    img.save(filename=dstfile_thumb)
                    im.add_image(dstfile_thumb)
            except wand.exceptions.MissingDelegateError:
                return HttpResponse(json.dumps({'success':False ,'error': 'input is not a valid image'}))
            return HttpResponse(json.dumps({'success':True ,'error': ''}))
        return HttpResponse( json.dumps({'success':False ,'error': 'Not a valid image file'}))

imagesearch/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description"  content="ImageSearch collects the best user interface designs and provides a search engine for you to find the similar images that you need." />
        <link rel="stylesheet" type="text/css" media="all" href="/static/css/style.css"/>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src = "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/static/js/file-uploader.js"></script>
    </head>
    <body class="home blog" ng-app = "myApp" ng-controller = "myCtrl">
        <div class="header-wrap">
            <div class="header">
                <ul class="nav clearfix">
                    <li class="item"><a href=""></a></li>
                    <li class="item compact">
                        <div class="menu menu-right">
                            <div class="block">
                                <ul class="sub-menu">
                                    <li><a href="">Browse</a></li>
                                    <li><a href="">Submit</a></li>
                                    <li><a href="">About</a></li>
                                    <li><a href="">Feedback</a></li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="item screen"><a href="{% url 'home' %}"><b id="logo">CueSearch</b></a></li>
                    <li class="item right">
                    <a href="" data-toggle="modal" data-target="#myModal"><i class="fa fa-upload" aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        {% url 'core:home' as home %}
        {% url 'core:search' as search %}
        <span id="top"></span>
        {% ifequal request.path search %}
            <div class="content-wrap background-1">
                <div class="content background_search">
                    {% include "updated_search_form.html" %}
        {% else %}
            <div class="content-wrap">
                <div class="content master-width clearfix">
                    {% include "search_form.html" %}
        {% endifequal %}
        </div>
        </div>
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                      <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Upload Images to Bank</h4>
                </div>
                <div class="modal-body">
                    {% include "modal_content.html" %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
      </div>
    </body>
    <script type="text/javascript">
        function ChangeText(oFileInput, sTargetID) {
            document.getElementById(sTargetID).value = oFileInput.value;
        }
    </script>
</html>

imagesearch/templates/modal_content.html
<form class="search" name="search_form" method="get" id="searchform" >
		<input class="search-input tab" type="text" id="modal_txt" value = "Choose File" 
	       onclick ="javascript:document.getElementById('file_modal').click();">
    <input class="btn" type="submit" name="submit" id="searchsubmit" value="Upload" ng-click = "uploadBank()">
</form>
<input id = "file_modal" type="file" style='visibility: hidden;' name="img" file-model = "myFile" onchange="ChangeText(this, 'modal_txt');"/>

imagesearch/templates/search_form.html
<h1 id="header_title">ImageSearch</h1>
<form class="search" name="search_form" method="get" id="searchform" >
		<input class="search-input tab" type="text"  id="txt" value = "Choose File" 
	       onclick ="javascript:document.getElementById('file').click();">
    <input class="btn" type="submit" name="submit" id="searchsubmitmain" value="Search" ng-click = "uploadFile()">
</form>
<input id = "file" type="file" style='visibility: hidden;' name="img" file-model = "myFile" onchange="ChangeText(this, 'txt');"/>

imagesearch/templates/search_response.html
{% extends "base.html" %}

imagesearch/templates/updated_search_form.html
{% load staticfiles %}
<form class="up_search" name="search_form" method="get" id="searchform">
    <span>
        <h2>
        	<input class="search-input tab" type="text" value="" name="s" id="s" onclick ="javascript:document.getElementById('file_up').click();"/>
            <input class="btn" type="submit" name="submit" id="searchsubmit" value="Search" ng-click = "uploadFile()"/>
        </h2>
    </span>
    {% if image_name %}
     <div class="sbib_d" id="sb_chc0"><a class="gscp_a" href="#" style="margin: 1px; line-height: 34px; height: 35px;"><img class="gscp_f" src={{media_url}}/{{image_name}} width="41" height="30" style="margin-bottom: 5px; "><span class="gscp_e"></span><span class="gscp_c">{{image_name}}</span><span class="gscp_d" onclick='this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode); document.getElementById("s").style.textAlign=" center"; window.location = "/"; return false;'>×</span></a></div>
    {% endif %}
</form>
<input id = "file_up" type="file" style='visibility: hidden;' name="img" file-model = "myFile" onchange="ChangeText(this, 's');"/>
<div class="row row_img">
    {% if image_matches %}
        {% for each in image_matches %}
        <div class="col-md-2">
    		<div class="img">
    		  <a target="_blank" href="img_fjords.jpg">
    		    <img src="/{{each.image}}">
                <em>Similarity : {{each.similarity}}</em>
    		  </a>
    		</div>
    	</div>
        {% endfor %}
    {% else %}
        <div class="col-md-4">
            <b style="color:#aaa;float: left;margin-left:-5px">Sorry, no results found! Please try again with another image</b>
        </div>
    {% endif %}
</div>